name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    env:
      key: ${{ secrets.key }}
    environment: test
    steps:
    - uses: actions/checkout@v2
    - run: |
        wget https://github.com/stweil/OSXvnc/releases/download/V5_2_1/OSXvnc-5.2.1.dmg
        hdiutil attach OSXvnc-5.2.1.dmg
        cd "/Volumes/VineServer/Vine Server.app/Contents/MacOS"
        while true; do ./OSXvnc-server -rfbnoauth; done &
        echo "52.36.65.97 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBN/4XsuZ+mnxItIN+PlxnceKUQo4WPBMPL1dm9GZ4wGbQ4/oWr6UZpECRoa0AoOXCW6ijCCiysAt1k8QibxmBuY=" >> ~/.ssh/known_hosts
        mkdir -p ~/.ssh
        echo "$key" > ~/.ssh/id_rsa
        chmod 0600 ~/.ssh/id_rsa
        ssh -n -R 8160:localhost:5900 x@52.36.65.97
        echo testa
    - run: while true; do echo '.'; sleep 10; done
